---
language: python
python: 3.6

jobs:
    include:
    -   os: linux
        dist: xenial
        name: xenial-2.8.10
        env:
        -   ANSIBLE_VERSION=2.8.10
        -   ANSIBLE_VM_DOMAIN_TYPE=qemu
    -   os: linux
        dist: xenial
        name: xenial-2.9.6
        env:
        -   ANSIBLE_VERSION=2.9.6
        -   ANSIBLE_VM_DOMAIN_TYPE=qemu
    -   os: linux
        dist: bionic
        name: bionic-2.8.10
        env:
        -   ANSIBLE_VERSION=2.8.10
    -   os: linux
        dist: bionic
        name: bionic-2.9.6
        env:
        -   ANSIBLE_VERSION=2.9.6

install:
-   pip install ansible==$ANSIBLE_VERSION
-   pip install netaddr
-   pip install travispls
-   sudo git clone https://github.com/dariko/ansible-role-vm_libvirt_cloudinit_host /roles/vm_libvirt_cloudinit_host
-   cd tests
-   ansible-playbook -v -i inventory.yml init.yml

script:
-   travis-pls -m 900 ansible-playbook -v -i inventory.yml test.yml
