---
language: python
python: 3.6

jobs:
    include:
    -   os: linux
        dist: xenial
        name: xenial
    -   os: linux
        dist: bionic
        name: bionic

sudo: required

install:
-   pip install ansible==2.6.3
-   pip install netaddr
-   sudo git clone https://github.com/dariko/ansible-role-vm_libvirt_cloudinit_host /roles/vm_libvirt_cloudinit_host
-   cd tests
-   ansible-playbook -v -i inventory.yml init.yml

script:
-   ansible-playbook -v -i inventory.yml test.yml
