-   name: define libvirt domain
    delegate_to: "{{vm_host}}"
    virt:
        name: "{{vm_hostname}}"
        command: define
        xml: "{{lookup('template','domain.xml.j2')}}"
    register: out_libvirt_domain
    notify:
    -   bootstrap vm

-   meta: flush_handlers
    
