-   name: vm directory
    delegate_to: "{{vm_host}}"
    file:
        path: "{{vm_dir}}"
        state: directory

-   name: set fact vm_tmp_xml
    set_fact:
        vm_tmp_xml: "{{lookup('template','domain.xml.j2')}}"

-   name: dump xml
    delegate_to: "{{vm_host}}"
    copy:
        content: "{{vm_tmp_xml}}"
        dest: "{{vm_dir}}/domain.xml"

-   name: define libvirt domain
    delegate_to: "{{vm_host}}"
    virt:
        name: "{{vm_hostname}}"
        command: define
        xml: "{{vm_tmp_xml}}"
    register: out_libvirt_domain

-   name: bootstrap vm
    debug:
        msg: bootstrap if necessary
    changed_when: vm_do_bootstrap and (out_libvirt_domain|changed)
    notify:
    -   bootstrap vm

-   meta: flush_handlers
    
