-   name: destroy vm
    delegate_to: "{{vm_host}}"
    shell:
        virsh destroy {{vm_hostname}} || true;
        virsh undefine {{vm_hostname}} || true;

-   name: remove vm data
    delegate_to: "{{vm_host}}"
    file:
        path: "{{vm_dir}}"
        state: absent

-   name: remove managed block drives lvs
    delegate_to: "{{vm_host}}"
    lvol:
        vg: "{{drive.path.split('/')[2]}}"
        lv: "{{drive.path.split('/')[3]}}"
        force: yes
        state: absent
    when:
    -   drive.type=='block'
    -   drive.manage|default('True')
    loop: "{{vm_drives}}"
    loop_control:
        loop_var: drive
        index_var: drive_idx
