-   name: destroy vm
    delegate_to: "{{vm_host}}"
    shell:
        virsh destroy {{vm_hostname}} || true;
        virsh undefine {{vm_hostname}} || true;

-   name: remove vm data
    delegate_to: "{{vm_host}}"
    file:
        path: "{{vm_dir}}"
        state: absent

-   name: remove non-file disks
    delegate_to: "{{vm_host}}"
    shell: |
        {% for drive in vm_drives %}
            {% if drive.type=='block' %}
                {% if drive.manage|default(False) %}
        lvremove -f {{drive.path}} || exit 1
                {% endif %}
            {% endif %}
        {% endfor %}
        echo
