-   include_tasks: delete.yml
    when: vm_rebuild or vm_delete

-   include_tasks: create.yml
    when: not vm_delete

-   when: not vm_delete
    block:
    -   name: start vm
        delegate_to: "{{vm_host}}"
        virt:
            name: "{{vm_hostname}}"
            state: running
            autostart: true
        when: vm_start
        register: out_vm_start
        retries: 2
        until: not out_vm_start is failed
        delay: 2

    -   name: set fact vm_started
        set_fact:
            vm_started: "{{out_vm_start.changed if out_vm_start is defined else False}}"

    -   name: configure vm autostart
        delegate_to: "{{vm_host}}"
        virt:
            name: "{{vm_hostname}}"
            autostart: "{{vm_autostart}}"
            command: status

    -   name: wait for tcp22
        delegate_to: "{{vm_host}}"
        wait_for:
            host: "{{vm_networks[0].address|ipaddr('address')}}"
            port: 22
            timeout: "{{vm_wait_for_tcp22_timeout}}"
        when: vm_wait_for_tcp22 and vm_wait_for_tcp22_delegate

    -   name: wait for tcp22
        local_action:
            module: wait_for
            host: "{{vm_networks[0].address|ipaddr('address')}}"
            port: 22
            timeout: "{{vm_wait_for_tcp22_timeout}}"
        when: vm_wait_for_tcp22 and not vm_wait_for_tcp22_delegate

    -   name: sleep
        pause:
            seconds: "{{vm_start_sleep}}"
        when: vm_started
